export interface IGag {
    name: GagName;
    track: TrackName;
    damage: number;
    inventory: number;
    isOrganic: boolean;
}


export enum GagName {
    Feather = "Feather",
    Megaphone = "Megaphone",
    Lipstick = "Lipstick",
    BambooCane = "Bamboo Cane",
    PixieDust = "Pixie Dust",
    JugglingBalls = "Juggling Balls",
    HighDive = "High Dive",
    BananaPeel = "Banana Peel",
    Rake = "Rake",
    Marbles = "Marbles",
    Quicksand = "Quicksand",
    Trapdoor = "Trapdoor",
    TNT = "TNT",
    Railroad = "Railroad",
    OneDollarBill = "One Dollar Bill",
    SmallMagnet = "Small Magnet",
    FiveDollarBill = "Five Dollar Bill",
    BigMagnet = "Big Magnet",
    TenDollarBill = "Ten Dollar Bill",
    HypnoGoggles = "Hypno Goggles",
    Presentation = "Presentation",
    BikeHorn = "Bike Horn",
    Whistle = "Whistle",
    Bugle = "Bugle",
    AoogahHorn = "Aoogah Horn",
    ElephantTrunk = "Elephant Trunk",
    Foghorn = "Foghorn",
    OperaSinger = "Opera Singer",
    Cupcake = "Cupcake",
    FruitPieSlice = "Fruit Pie Slice",
    CreamPieSlice = "Cream Pie Slice",
    WholeFruitPie = "Whole Fruit Pie", 
    WholeCreamPie = "WholeC ream Pie", 
    BirthdayCake = "Birthday Cake", 
    WeddingCake = "Wedding Cake", 
    SquirtingFlower = "Squirting Flower", 
    GlassOfWater = "Glass Of Water", 
    SquirtGun = "Squirt Gun",  
    SeltzerBottle = "Seltzer Bottle", 
    FireHose = "Fire Hose", 
    StormClouds = "Storm Clouds", 
    Geyser = "Geyser", 
    FlowerPot = "Flower Pot", 
    Sandbag = "Sandbag", 
    Anvil = "Anvil", 
    BigWeight = "Big Weight", 
    Safe = "Safe", 
    GrandPiano = "Grand Piano", 
    Toontanic = "Toontanic",
}

export enum TrackName {
    Toonup = "Toon-up",
    Trap = "Trap",
    Lure = "Lure",
    Sound = "Sound",
    Throw = "Throw",
    Squirt = "Squirt",
    Drop = "Drop"
}

export const GagTracks: Record<GagName, TrackName> = {
    [GagName.Feather]: TrackName.Toonup,
    [GagName.Megaphone]: TrackName.Toonup,
    [GagName.Lipstick]: TrackName.Toonup,
    [GagName.BambooCane]: TrackName.Toonup,
    [GagName.PixieDust]: TrackName.Toonup,
    [GagName.JugglingBalls]: TrackName.Toonup,
    [GagName.HighDive]: TrackName.Toonup,
    [GagName.BananaPeel]: TrackName.Trap,
    [GagName.Rake]: TrackName.Trap,
    [GagName.Marbles]: TrackName.Trap,
    [GagName.Quicksand]: TrackName.Trap,
    [GagName.Trapdoor]: TrackName.Trap,
    [GagName.TNT]: TrackName.Trap,
    [GagName.Railroad]: TrackName.Trap,
    [GagName.OneDollarBill]: TrackName.Lure,
    [GagName.SmallMagnet]: TrackName.Lure,
    [GagName.FiveDollarBill]: TrackName.Lure,
    [GagName.BigMagnet]: TrackName.Lure,
    [GagName.TenDollarBill]: TrackName.Lure,
    [GagName.HypnoGoggles]: TrackName.Lure,
    [GagName.Presentation]: TrackName.Lure,
    [GagName.BikeHorn]: TrackName.Sound,
    [GagName.Whistle]: TrackName.Sound,
    [GagName.Bugle]: TrackName.Sound,
    [GagName.AoogahHorn]: TrackName.Sound,
    [GagName.ElephantTrunk]: TrackName.Sound,
    [GagName.Foghorn]: TrackName.Sound,
    [GagName.OperaSinger]: TrackName.Sound,
    [GagName.Cupcake]: TrackName.Throw,
    [GagName.FruitPieSlice]: TrackName.Throw,
    [GagName.CreamPieSlice]: TrackName.Throw,
    [GagName.WholeFruitPie]: TrackName.Throw,
    [GagName.WholeCreamPie]: TrackName.Throw,
    [GagName.BirthdayCake]: TrackName.Throw,
    [GagName.WeddingCake]: TrackName.Throw,
    [GagName.SquirtingFlower]: TrackName.Squirt,
    [GagName.GlassOfWater]: TrackName.Squirt,
    [GagName.SquirtGun]: TrackName.Squirt,
    [GagName.SeltzerBottle]: TrackName.Squirt,
    [GagName.FireHose]: TrackName.Squirt,
    [GagName.StormClouds]: TrackName.Squirt,
    [GagName.Geyser]: TrackName.Squirt,
    [GagName.FlowerPot]: TrackName.Drop,
    [GagName.Sandbag]: TrackName.Drop,
    [GagName.Anvil]: TrackName.Drop,
    [GagName.BigWeight]: TrackName.Drop,
    [GagName.Safe]: TrackName.Drop,
    [GagName.GrandPiano]: TrackName.Drop,
    [GagName.Toontanic]: TrackName.Drop,
};

export const MinGagDamage: Record<GagName, number> = {
    [GagName.Feather]: 8,
    [GagName.Megaphone]: 15,
    [GagName.Lipstick]: 27,
    [GagName.BambooCane]: 40,
    [GagName.PixieDust]: 50,
    [GagName.JugglingBalls]: 75,
    [GagName.HighDive]: 210,
    [GagName.BananaPeel]: 10,
    [GagName.Rake]: 18,
    [GagName.Marbles]: 30,
    [GagName.Quicksand]: 45,
    [GagName.Trapdoor]: 75,
    [GagName.TNT]: 90,
    [GagName.Railroad]: 200,
    [GagName.OneDollarBill]: 0,
    [GagName.SmallMagnet]: 0,
    [GagName.FiveDollarBill]: 0,
    [GagName.BigMagnet]: 0,
    [GagName.TenDollarBill]: 0,
    [GagName.HypnoGoggles]: 0,
    [GagName.Presentation]: 0,
    [GagName.BikeHorn]: 3,
    [GagName.Whistle]: 5,
    [GagName.Bugle]: 9,
    [GagName.AoogahHorn]: 14,
    [GagName.ElephantTrunk]: 19,
    [GagName.Foghorn]: 25,
    [GagName.OperaSinger]: 90,
    [GagName.Cupcake]: 4,
    [GagName.FruitPieSlice]: 8,
    [GagName.CreamPieSlice]: 14,
    [GagName.WholeFruitPie]: 24,
    [GagName.WholeCreamPie]: 36,
    [GagName.BirthdayCake]: 48,
    [GagName.WeddingCake]: 100,
    [GagName.SquirtingFlower]: 3,
    [GagName.GlassOfWater]: 6,
    [GagName.SquirtGun]: 10,
    [GagName.SeltzerBottle]: 18,
    [GagName.FireHose]: 27,
    [GagName.StormClouds]: 36,
    [GagName.Geyser]: 105,
    [GagName.FlowerPot]: 10,
    [GagName.Sandbag]: 18,
    [GagName.Anvil]: 30,
    [GagName.BigWeight]: 45,
    [GagName.Safe]: 60,
    [GagName.GrandPiano]: 85,
    [GagName.Toontanic]: 180,
};

export const MaxGagDamage: Record<GagName, number> = {
    [GagName.Feather]: 10,
    [GagName.Megaphone]: 18,
    [GagName.Lipstick]: 30,
    [GagName.BambooCane]: 45,
    [GagName.PixieDust]: 60,
    [GagName.JugglingBalls]: 105,
    [GagName.HighDive]: 210,
    [GagName.BananaPeel]: 12,
    [GagName.Rake]: 20,
    [GagName.Marbles]: 35,
    [GagName.Quicksand]: 50,
    [GagName.Trapdoor]: 85,
    [GagName.TNT]: 180,
    [GagName.Railroad]: 200,
    [GagName.OneDollarBill]: 0,
    [GagName.SmallMagnet]: 0,
    [GagName.FiveDollarBill]: 0,
    [GagName.BigMagnet]: 0,
    [GagName.TenDollarBill]: 0,
    [GagName.HypnoGoggles]: 0,
    [GagName.Presentation]: 0,
    [GagName.BikeHorn]: 4,
    [GagName.Whistle]: 7,
    [GagName.Bugle]: 11,
    [GagName.AoogahHorn]: 16,
    [GagName.ElephantTrunk]: 21,
    [GagName.Foghorn]: 50,
    [GagName.OperaSinger]: 90,
    [GagName.Cupcake]: 6,
    [GagName.FruitPieSlice]: 10,
    [GagName.CreamPieSlice]: 17,
    [GagName.WholeFruitPie]: 27,
    [GagName.WholeCreamPie]: 40,
    [GagName.BirthdayCake]: 100,
    [GagName.WeddingCake]: 120,
    [GagName.SquirtingFlower]: 4,
    [GagName.GlassOfWater]: 8,
    [GagName.SquirtGun]: 12,
    [GagName.SeltzerBottle]: 21,
    [GagName.FireHose]: 30,
    [GagName.StormClouds]: 80,
    [GagName.Geyser]: 105,
    [GagName.FlowerPot]: 10,
    [GagName.Sandbag]: 18,
    [GagName.Anvil]: 30,
    [GagName.BigWeight]: 45,
    [GagName.Safe]: 70,
    [GagName.GrandPiano]: 170,
    [GagName.Toontanic]: 180,
};
